### PR TITLE
MAISTRA-1629: add support for excludeOutboundPorts

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Review by luksa — APPROVED** [review]
LGTM, but note that the `includePorts` field was renamed to `includeInboundPorts` upstream (in the same PR that added `includeOutboundPorts`). It may make sense to do the same in this PR, just to make rebasing in the future easier.

**Comment by knrc** [comment]
@luksa +1, however the annotation is still correct and it's just the field name.  We should make that a separate change and not pollute this fix with extra changes.

**Review by jwendell — APPROVED** [review]
We have https://issues.redhat.com/browse/MAISTRA-1233 that would cover this and what Marko suggested.

**Comment by knrc** [comment]
@jwendell We can deal with @luksa's issue in that one, if it gets scheduled.  In the meantime this PR addresses the specific issue at hand

**Pull request merged**
